package all_insure;
import java.awt.*;
import javax.swing.*;
public class MainPageFrame extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JButton getQuotesBtn;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane intro1ScrollPane;
    private javax.swing.JScrollPane intro2ScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea intro1TextArea;
    private javax.swing.JTextArea intro2TextArea;
    private javax.swing.JLabel signInLbl;
    private javax.swing.JButton editAccBtn;
    private javax.swing.JLabel signUpLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration 
    
    public MainPageFrame() {
        super("Main Page");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signUpLbl = new javax.swing.JLabel("Sign Up!");
        signUpLbl.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        signUpLbl.setForeground(new java.awt.Color(0, 153, 102));
        signUpLbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                signUpAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        signUpLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpMouseExited(evt);
            }
        });

        signInLbl = new javax.swing.JLabel("Sign in");
        signInLbl.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        signInLbl.setForeground(new java.awt.Color(0, 153, 102));
        signInLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        titleLbl = new javax.swing.JLabel("MyInsure");
        titleLbl.setFont(new java.awt.Font("SimSun-ExtB", 3, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 153, 102));

        iconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all_insure/all.png"))); // NOI18N

        getQuotesBtn = new javax.swing.JButton("Get Quotes!");
        getQuotesBtn.setBackground(new java.awt.Color(0, 153, 102));
        getQuotesBtn.setForeground(new java.awt.Color(255, 255, 255));
        getQuotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getQuotesActionPerformed(evt);
            }
        });

        editAccBtn = new javax.swing.JButton("Edit Account");
        editAccBtn.setBackground(new java.awt.Color(0, 153, 102));
        editAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        editAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccActionPerformed(evt);
            }
        });

        intro1ScrollPane = new javax.swing.JScrollPane();
        intro1ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        intro1ScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        intro1TextArea = new javax.swing.JTextArea();
        intro1TextArea.setEditable(false);
        intro1TextArea.setColumns(20);
        intro1TextArea.setRows(5);
        intro1TextArea.setText("We offer a many types \nof insurance\n........");
        intro1ScrollPane.setViewportView(intro1TextArea);

        intro2ScrollPane = new javax.swing.JScrollPane();
        intro2ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        intro2ScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        intro2TextArea = new javax.swing.JTextArea();
        intro2TextArea.setEditable(false);
        intro2TextArea.setColumns(20);
        intro2TextArea.setRows(5);
        intro2TextArea.setText("More text....\n\n");
        intro2ScrollPane.setViewportView(intro2TextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(iconLbl)
                .addGap(43, 43, 43)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signInLbl)
                    .addComponent(signUpLbl))
                .addGap(18, 18, 18))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intro1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editAccBtn)
                    .addComponent(getQuotesBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intro2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(signInLbl)
                                .addGap(18, 18, 18)
                                .addComponent(signUpLbl))))
                    .addComponent(iconLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(getQuotesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editAccBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(intro2ScrollPane)
                            .addComponent(intro1ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    private void loginMouseClicked(java.awt.event.MouseEvent evt) {                                   
        if(Main.mainPageFrm.getSignInLbl().getText().equals("Sign Out")){
            JOptionPane.showMessageDialog(this, "You have been signed out!");
            Main.signInFrm.loggedIn = false;
            Main.mainPageFrm.getSignInLbl().setText("Login");
            Main.mainPageFrm.getSignUpLbl().setText("Sign Up");
            Main.mainPageFrm.revalidate();
            Main.mainPageFrm.repaint();
        }
        else{
            Main.signInFrm.setVisible(true);
        }
        
    }                                  

    public JLabel getSignInLbl() {
        return signInLbl;
    }
    
    public JLabel getSignUpLbl() {
        return signUpLbl;
    }
    
    private void getQuotesActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Main.quoteSelectFrm.setVisible(true);

    }                                         

    private void manageAccActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Main.edit.setVisible(true);
    }                                         

    private void signUpAncestorAdded(javax.swing.event.AncestorEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {                                    
        Main.signUpFrm.setVisible(true);
    }                                   

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {                                   
        signInLbl.setForeground(Color.blue);
        MainPageFrame.this.revalidate();
        MainPageFrame.this.repaint();
    }                                  

    private void loginMouseExited(java.awt.event.MouseEvent evt) {                                  
        signInLbl.setForeground(titleLbl.getForeground());
        MainPageFrame.this.revalidate();
        MainPageFrame.this.repaint();
    }                                 

    private void signUpMouseEntered(java.awt.event.MouseEvent evt) {                                    
        signUpLbl.setForeground(Color.blue);
        MainPageFrame.this.revalidate();
        MainPageFrame.this.repaint();
    }                                   

    private void signUpMouseExited(java.awt.event.MouseEvent evt) {                                   
        signUpLbl.setForeground(titleLbl.getForeground());
        MainPageFrame.this.revalidate();
        MainPageFrame.this.repaint();
    }                                  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageFrame().setVisible(true);
            }
        });
    }

                      
}
