package all_insure;
import javax.swing.*;


public class SignInFrame extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logLogBut;
    private javax.swing.JLabel logPassLabel;
    private javax.swing.JPasswordField logPassText;
    private javax.swing.JButton logSignBut;
    private javax.swing.JLabel logUserLabel;
    private javax.swing.JTextField logUserText;
    private javax.swing.JPanel login;
    
    // End of variables declaration  
    public boolean loggedIn = false;
    
    public SignInFrame() {
        super("Log in ");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logUserLabel = new javax.swing.JLabel();
        logPassLabel = new javax.swing.JLabel();
        logUserText = new javax.swing.JTextField();
        logLogBut = new javax.swing.JButton();
        logSignBut = new javax.swing.JButton();
        logPassText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all_insure/Alinsure.png"))); // NOI18N

        logUserLabel.setFont(new java.awt.Font("Lucida Sans", 3, 14)); // NOI18N
        logUserLabel.setForeground(new java.awt.Color(0, 153, 102));
        logUserLabel.setText("Username");

        logPassLabel.setFont(new java.awt.Font("Lucida Sans", 3, 14)); // NOI18N
        logPassLabel.setForeground(new java.awt.Color(0, 153, 102));
        logPassLabel.setText("Password ");

        logLogBut.setBackground(new java.awt.Color(0, 153, 102));
        logLogBut.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        logLogBut.setForeground(new java.awt.Color(255, 255, 255));
        logLogBut.setText("Login");
        logLogBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logLogButMouseClicked(evt);
            }
        });
//        logLogBut.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                logLogButActionPerformed(evt);
//            }
//        });

        logSignBut.setBackground(new java.awt.Color(0, 153, 102));
        logSignBut.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        logSignBut.setForeground(new java.awt.Color(255, 255, 255));
        logSignBut.setText("Sign Up");
        logSignBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logSignButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logPassLabel)
                    .addComponent(logLogBut)
                    .addComponent(logUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logUserText)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(logSignBut)
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addComponent(logPassText))
                .addContainerGap())
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logUserLabel)
                            .addComponent(logUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logPassLabel)
                            .addComponent(logPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logLogBut)
                            .addComponent(logSignBut)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void logLogButMouseClicked(java.awt.event.MouseEvent evt) {                                       
        //checking if username/password is correct. needs actual reference to user class
        if("Username".equals(logUserText.getText()) && "Password".equals(logPassText.getPassword())){
           //call application
       }
    }                                      

    private void logSignButMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //using initialised SignInFrame and SignUpFrame classes in main class to change views
        Main.signInFrm.setVisible(false);
        Main.signUpFrm.setVisible(true);
    }                                       

    public void logLogButActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //if( login deatails are staffFrm account) {}
        if(logUserText.getText().equals("staff") && String.valueOf(logPassText.getPassword()).equals("staff")){
            Main.staffFrm.setVisible(true);
        }
        loggedIn = true;
        Main.mainPageFrm.getSignInLbl().setText("Sign Out");
        Main.mainPageFrm.getSignUpLbl().setText("");
        Main.mainPageFrm.revalidate();
        Main.mainPageFrm.repaint();
        Main.signInFrm.setVisible(false);
        
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFrame().setVisible(true);                
            }
        });
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JButton getLogLogBut() {
        return logLogBut;
    }

    public JLabel getLogPassLabel() {
        return logPassLabel;
    }

    public JPasswordField getLogPassText() {
        return logPassText;
    }

    public JButton getLogSignBut() {
        return logSignBut;
    }

    public JLabel getLogUserLabel() {
        return logUserLabel;
    }

    public JTextField getLogUserText() {
        return logUserText;
    }

    public JPanel getLogin() {
        return login;
    }

    public boolean isLoggedIn() {
        return loggedIn;
    }
    
    

                     
}
